'use client';
import Link from 'next/link';
import {useState} from 'react';
import {DEMO_ACCOUNT_FUNCTION_URL,SUPABASE_PUBLISHABLE_KEY} from '@/lib/supabase/config';
import {ArrowRight,Building2,CheckCircle2,UserRound,Warehouse} from 'lucide-react';

type Role='patient'|'pharmacy'|'provider';
const options=[['patient','Patient',UserRound,'Create a personal workspace'],['pharmacy','Pharmacy',Warehouse,'Create a pharmacy workspace'],['provider','Provider organization',Building2,'Create a provider workspace']] as const;

export default function Register(){
 const[role,setRole]=useState<Role>('patient'); const[email,setEmail]=useState(''); const[password,setPassword]=useState(''); const[organization,setOrganization]=useState(''); const[name,setName]=useState(''); const[message,setMessage]=useState(''); const[error,setError]=useState(''); const[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');setError('');
  try{const res=await fetch(DEMO_ACCOUNT_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_PUBLISHABLE_KEY},body:JSON.stringify({role,email,password,organization_name:organization,name:name||'Demo Patient'})}); const body=await res.json().catch(()=>({})); if(!res.ok){throw new Error(body.error||'Could not create the account.');} setMessage('Account created. You can sign in now — no email confirmation is required for this demo.'); setPassword('');}catch(e){setError(e instanceof Error?e.message:'Could not create the account.');} finally{setBusy(false)}}
 return <main className="min-h-screen bg-mist px-5 py-8 md:py-10"><div className="mx-auto max-w-5xl"><div className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-ink text-white">M</span>Med<span className="text-mint">Relay</span></Link><Link href="/login" className="text-sm font-semibold text-slate-600">Already have access? Sign in</Link></div><div className="mt-10 rounded-[32px] border border-line bg-white p-7 shadow-xl md:p-10"><div className="max-w-3xl"><div className="text-sm font-bold uppercase tracking-widest text-mint">Demo account setup</div><h1 className="display mt-2 text-4xl font-extrabold md:text-5xl">Create the workspace you want to explore.</h1><p className="mt-4 text-lg leading-8 text-slate-500">For this hackathon demo, all three workspace types can be created directly. Email verification is intentionally skipped so judges can get straight into the product.</p></div>
 <div className="mt-8 grid gap-3 md:grid-cols-3">{options.map(([r,t,I,d])=>{const Icon=I;return <button type="button" key={r} onClick={()=>{setRole(r);setMessage('');setError('')}} className={`rounded-2xl border p-5 text-left transition ${role===r?'border-mint bg-mist shadow-sm':'border-line hover:border-slate-300'}`}><Icon size={21} className={role===r?'text-mint':'text-slate-400'}/><div className="mt-5 font-bold">{t}</div><div className="mt-1 text-xs text-slate-500">{d}</div></button>})}</div>
 <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5"><div className="font-bold text-amber-900">Demo-only organization access</div><p className="mt-2 text-sm leading-6 text-amber-800">For this demo, we allow you to create a pharmacy or provider organization immediately. In production, a MedRelay administrator would review the application, verify the organization or pharmacy, and then grant workspace access.</p></div>
 <form onSubmit={submit} className="mt-8 grid gap-5 md:max-w-2xl"><label><span className="text-sm font-semibold">Email / login identifier</span><input required type="text" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-line px-4 py-3.5 outline-none focus:border-mint" placeholder="anything@test.com"/><span className="mt-1 block text-xs text-slate-400">Any normal email-style domain works in this demo; Gmail is not required.</span></label>{role==='patient'&&<label><span className="text-sm font-semibold">Name</span><input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-line px-4 py-3.5 outline-none focus:border-mint" placeholder="Your name"/></label>}{role!=='patient'&&<label><span className="text-sm font-semibold">{role==='pharmacy'?'Pharmacy name':'Provider organization name'}</span><input required value={organization} onChange={e=>setOrganization(e.target.value)} className="mt-2 w-full rounded-xl border border-line px-4 py-3.5 outline-none focus:border-mint" placeholder={role==='pharmacy'?'Example Pharmacy':'Example Medical Group'}/></label>}<label><span className="text-sm font-semibold">Password</span><input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-line px-4 py-3.5 outline-none focus:border-mint" placeholder="At least 8 characters"/></label>{message&&<div className="flex items-start gap-3 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 size={18} className="mt-0.5 shrink-0"/>{message}</div>}{error&&<div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<button disabled={busy} className="flex items-center justify-center gap-2 rounded-xl bg-ink py-3.5 font-semibold text-white disabled:opacity-60">{busy?'Creating account…':'Create account'} <ArrowRight size={17}/></button></form>
 </div></div></main>
}
