alter function public.is_pharmacy_member(uuid) set search_path=public;
alter function public.is_provider_member(uuid) set search_path=public;
alter function public.is_patient_owner(uuid) set search_path=public;
revoke execute on function public.handle_new_user() from public, anon, authenticated;
create index if not exists audit_logs_actor_id_idx on public.audit_logs(actor_id);
create index if not exists documents_uploaded_by_idx on public.documents(uploaded_by);
create index if not exists pharmacy_memberships_pharmacy_id_idx on public.pharmacy_memberships(pharmacy_id);
create index if not exists prescriptions_medication_id_idx on public.prescriptions(medication_id);
create index if not exists prescriptions_source_document_id_idx on public.prescriptions(source_document_id);
create index if not exists provider_memberships_org_id_idx on public.provider_memberships(provider_organization_id);
create index if not exists refill_requests_requested_by_idx on public.refill_requests(requested_by);
create unique index if not exists one_active_refill_per_prescription on public.refill_requests(prescription_id) where status not in ('COMPLETED','CANCELLED','PROVIDER_REJECTED');
create or replace function public.complete_refill_updates_prescription() returns trigger language plpgsql set search_path=public as $$ begin if new.status='COMPLETED' and old.status<>'COMPLETED' then update public.prescriptions set refills_used=refills_used+1,updated_at=now() where id=new.prescription_id and refills_used<refills_authorized; end if; return new; end; $$;
drop trigger if exists refill_completion_updates_prescription on public.refill_requests;
create trigger refill_completion_updates_prescription after update of status on public.refill_requests for each row execute function public.complete_refill_updates_prescription();
drop policy if exists patients_select_self on public.patients;
drop policy if exists patients_select_pharmacy on public.patients;
drop policy if exists patients_select_provider on public.patients;
drop policy if exists patients_select_visible on public.patients;
create policy patients_select_visible on public.patients for select to authenticated using (user_id=(select auth.uid()) or exists(select 1 from public.prescriptions p where p.patient_id=id and p.pharmacy_id is not null and public.is_pharmacy_member(p.pharmacy_id)) or exists(select 1 from public.prescriptions p where p.patient_id=id and p.provider_organization_id is not null and public.is_provider_member(p.provider_organization_id)));
drop policy if exists prescriptions_select_patient on public.prescriptions;
drop policy if exists prescriptions_select_pharmacy on public.prescriptions;
drop policy if exists prescriptions_select_provider on public.prescriptions;
drop policy if exists prescriptions_select_visible on public.prescriptions;
create policy prescriptions_select_visible on public.prescriptions for select to authenticated using (public.is_patient_owner(patient_id) or (pharmacy_id is not null and public.is_pharmacy_member(pharmacy_id)) or (provider_organization_id is not null and public.is_provider_member(provider_organization_id)));
drop policy if exists refill_insert_patient on public.refill_requests;
drop policy if exists refill_insert_pharmacy on public.refill_requests;
drop policy if exists refill_insert_allowed on public.refill_requests;
create policy refill_insert_allowed on public.refill_requests for insert to authenticated with check (requested_by=(select auth.uid()) and (exists(select 1 from public.prescriptions p where p.id=prescription_id and public.is_patient_owner(p.patient_id)) or exists(select 1 from public.prescriptions p where p.id=prescription_id and p.pharmacy_id is not null and public.is_pharmacy_member(p.pharmacy_id))));
drop policy if exists refill_select_patient on public.refill_requests;
drop policy if exists refill_select_pharmacy on public.refill_requests;
drop policy if exists refill_select_provider on public.refill_requests;
drop policy if exists refill_select_visible on public.refill_requests;
create policy refill_select_visible on public.refill_requests for select to authenticated using (exists(select 1 from public.prescriptions p where p.id=prescription_id and public.is_patient_owner(p.patient_id)) or exists(select 1 from public.prescriptions p where p.id=prescription_id and p.pharmacy_id is not null and public.is_pharmacy_member(p.pharmacy_id)) or exists(select 1 from public.prescriptions p where p.id=prescription_id and p.provider_organization_id is not null and public.is_provider_member(p.provider_organization_id)));
drop policy if exists refill_update_pharmacy on public.refill_requests;
drop policy if exists refill_update_provider on public.refill_requests;
drop policy if exists refill_update_allowed on public.refill_requests;
create policy refill_update_allowed on public.refill_requests for update to authenticated using (exists(select 1 from public.prescriptions p where p.id=prescription_id and p.pharmacy_id is not null and public.is_pharmacy_member(p.pharmacy_id)) or exists(select 1 from public.prescriptions p where p.id=prescription_id and p.provider_organization_id is not null and public.is_provider_member(p.provider_organization_id))) with check (exists(select 1 from public.prescriptions p where p.id=prescription_id and p.pharmacy_id is not null and public.is_pharmacy_member(p.pharmacy_id)) or exists(select 1 from public.prescriptions p where p.id=prescription_id and p.provider_organization_id is not null and public.is_provider_member(p.provider_organization_id)));
